const fs = require('fs');
const SparkMD5 = require('spark-md5');

const xml = `<?xml version='1.0' encoding='ISO-8859-1'?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas">
  <ans:cabecalho>
    <ans:identificacaoTransacao>
      <ans:tipoTransacao>ENVIO_LOTE_GUIAS</ans:tipoTransacao>
      <ans:sequencialTransacao>2026678</ans:sequencialTransacao>
      <ans:dataRegistroTransacao>2026-09-04</ans:dataRegistroTransacao>
      <ans:horaRegistroTransacao>16:05:19</ans:horaRegistroTransacao>
    </ans:identificacaoTransacao>
    <ans:origem>
      <ans:identificacaoPrestador>
        <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
      </ans:identificacaoPrestador>
    </ans:origem>
    <ans:destino>
      <ans:registroANS>326305</ans:registroANS>
    </ans:destino>
    <ans:Padrao>4.01.00</ans:Padrao>
  </ans:cabecalho>
  <ans:prestadorParaOperadora>
    <ans:loteGuias>
      <ans:numeroLote>3647023</ans:numeroLote>
      <ans:guiasTISS>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>515626750</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>515626750</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-09</ans:dataAutorizacao>
            <ans:senha>EX2026014217297</ans:senha>
            <ans:dataValidadeSenha>2026-08-09</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>077050268</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>OUTRAS INFORMACOES</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-09</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-09</ans:dataExecucao>
              <ans:horaInicial>09:05:00</ans:horaInicial>
              <ans:horaFinal>09:35:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>150.50</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>150.50</ans:valorUnitario>
              <ans:valorTotal>150.50</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>09341842751</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>OUTRAS INFORMACOES</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-07-09</ans:dataExecucao>
              <ans:horaInicial>09:45:00</ans:horaInicial>
              <ans:horaFinal>10:15:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>215.00</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>215.00</ans:valorUnitario>
              <ans:valorTotal>215.00</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>09341842751</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>OUTRAS INFORMACOES</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>365.50</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>350.20</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>516608619</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>516608619</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-09</ans:dataAutorizacao>
            <ans:senha>EX2026014621295</ans:senha>
            <ans:dataValidadeSenha>2026-08-09</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>077050268</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>OUTRAS INFORMACOES</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-09</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-09</ans:dataExecucao>
              <ans:horaInicial>08:45:43</ans:horaInicial>
              <ans:horaFinal>09:15:43</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301315</ans:codigoProcedimento>
                <ans:descricaoProcedimento>RETINOGRAFIA (S? HONOR?RIO) MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>19.20</ans:valorUnitario>
              <ans:valorTotal>38.40</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>09341842751</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>OUTRAS INFORMACOES</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-07-09</ans:dataExecucao>
              <ans:horaInicial>09:25:43</ans:horaInicial>
              <ans:horaFinal>09:55:43</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301080</ans:codigoProcedimento>
                <ans:descricaoProcedimento>CERATOSCOPIA COMPUTADORIZADA - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>46.35</ans:valorUnitario>
              <ans:valorTotal>92.70</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>09341842751</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>OUTRAS INFORMACOES</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>8400</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>131.10</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>131.10</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>525559860</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>525559860</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-31</ans:dataAutorizacao>
            <ans:senha>CO2026009462760</ans:senha>
            <ans:dataValidadeSenha>2026-08-31</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>885076990</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>LEONARDO VIEIRA</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-31</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>04</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-31</ans:dataExecucao>
              <ans:horaInicial>08:07:22</ans:horaInicial>
              <ans:horaFinal>08:37:22</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>98</ans:codigoTabela>
                <ans:codigoProcedimento>91000184</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PCT CONSULTA OFTALMOLOGIA BASICA [C/HNN]</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>95.30</ans:valorUnitario>
              <ans:valorTotal>95.30</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>95.30</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>95.30</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>516306065</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>516306065</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-30</ans:dataAutorizacao>
            <ans:senha>EX2026014498875</ans:senha>
            <ans:dataValidadeSenha>2026-09-06</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>300971737</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>RUBENS MACHADO</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-30</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>H40 - GLAUCOMA</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-30</ans:dataExecucao>
              <ans:horaInicial>12:40:00</ans:horaInicial>
              <ans:horaFinal>13:10:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA- MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>150.50</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>150.50</ans:valorUnitario>
              <ans:valorTotal>150.50</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>25208586134</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>RUBENS MACHADO</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-07-30</ans:dataExecucao>
              <ans:horaInicial>13:20:00</ans:horaInicial>
              <ans:horaFinal>13:50:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>215.00</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>215.00</ans:valorUnitario>
              <ans:valorTotal>215.00</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>25208586134</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>RUBENS MACHADO</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>365.50</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>350.20</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>520174416</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>520174416</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-30</ans:dataAutorizacao>
            <ans:senha>EX2026016352025</ans:senha>
            <ans:dataValidadeSenha>2026-09-06</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>300971737</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>RUBENS MACHADO</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-30</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>H40 - GLAUCOMA</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-30</ans:dataExecucao>
              <ans:horaInicial>11:30:00</ans:horaInicial>
              <ans:horaFinal>12:00:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301250</ans:codigoProcedimento>
                <ans:descricaoProcedimento>MAPEAMENTO DE RETINA (OFTALMOSCOPIA INDIRETA) - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>52.73</ans:valorUnitario>
              <ans:valorTotal>105.46</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>25208586134</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>RUBENS MACHADO</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>105.46</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>105.46</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>520176329</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>520176329</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-30</ans:dataAutorizacao>
            <ans:senha>CO2026008218084</ans:senha>
            <ans:dataValidadeSenha>2026-09-29</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>300971737</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>RUBENS MACHADO</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-30</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>H40 - GLAUCOMA</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>04</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-30</ans:dataExecucao>
              <ans:horaInicial>10:52:39</ans:horaInicial>
              <ans:horaFinal>11:22:39</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>98</ans:codigoTabela>
                <ans:codigoProcedimento>91000184</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PCT CONSULTA OFTALMOLOGIA BASICA [C/HNN]</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>95.30</ans:valorUnitario>
              <ans:valorTotal>95.30</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>25208586134</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>RUBENS MACHADO</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>95.30</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>95.30</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>525323433</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>525323433</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-28</ans:dataAutorizacao>
            <ans:senha>CO2026009413420</ans:senha>
            <ans:dataValidadeSenha>2026-09-28</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>097862802</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>GUILHERME AZEVEDO FRACALOSSI</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>15848</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-28</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>04</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-28</ans:dataExecucao>
              <ans:horaInicial>10:47:23</ans:horaInicial>
              <ans:horaFinal>11:17:23</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>98</ans:codigoTabela>
                <ans:codigoProcedimento>91000184</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PCT CONSULTA OFTALMOLOGIA BASICA [C/HNN]</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>95.30</ans:valorUnitario>
              <ans:valorTotal>95.30</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>14788544725</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>GUILHERME AZEVEDO FRACALOSSI</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15848</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>95.30</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>95.30</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>518198766</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>518198766</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-07</ans:dataAutorizacao>
            <ans:senha>EX2026015500775</ans:senha>
            <ans:dataValidadeSenha>2026-10-07</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>079510584</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>RUBENS MACHADO</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-07</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-07</ans:dataExecucao>
              <ans:horaInicial>11:25:09</ans:horaInicial>
              <ans:horaFinal>11:55:09</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>150.50</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>150.50</ans:valorUnitario>
              <ans:valorTotal>150.50</ans:valorTotal>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-08-07</ans:dataExecucao>
              <ans:horaInicial>12:05:09</ans:horaInicial>
              <ans:horaFinal>12:35:09</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>215.00</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>215.00</ans:valorUnitario>
              <ans:valorTotal>215.00</ans:valorTotal>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>365.50</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>350.20</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>520838313</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>520838313</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-14</ans:dataAutorizacao>
            <ans:senha>EX2026016785056</ans:senha>
            <ans:dataValidadeSenha>2026-08-14</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>089315841</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>LEONARDO VIEIRA</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-14</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>16:25:00</ans:horaInicial>
              <ans:horaFinal>16:55:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>150.50</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>150.50</ans:valorUnitario>
              <ans:valorTotal>150.50</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>17:05:00</ans:horaInicial>
              <ans:horaFinal>17:35:00</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501144</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TOMOGRAFIA DE COER?NCIA ?PTICA  MONOCULAR</ans:descricaoProcedimento>
                <ans:valorProcedimento>215.00</ans:valorProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:viaAcesso>1</ans:viaAcesso>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>215.00</ans:valorUnitario>
              <ans:valorTotal>215.00</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>365.50</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>350.20</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>522868544</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>522868544</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-14</ans:dataAutorizacao>
            <ans:senha>EX2026017655118</ans:senha>
            <ans:dataValidadeSenha>2026-08-14</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>089315841</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>LEONARDO VIEIRA</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-14</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>13:15:28</ans:horaInicial>
              <ans:horaFinal>13:45:28</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301080</ans:codigoProcedimento>
                <ans:descricaoProcedimento>CERATOSCOPIA COMPUTADORIZADA - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>46.35</ans:valorUnitario>
              <ans:valorTotal>92.70</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>2</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>13:55:28</ans:horaInicial>
              <ans:horaFinal>14:25:28</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>40103137</ans:codigoProcedimento>
                <ans:descricaoProcedimento>CAMPIMETRIA COMPUTADORIZADA - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>25.60</ans:valorUnitario>
              <ans:valorTotal>51.20</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>3</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>14:35:28</ans:horaInicial>
              <ans:horaFinal>15:05:28</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301315</ans:codigoProcedimento>
                <ans:descricaoProcedimento>RETINOGRAFIA (S? HONOR?RIO) MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>2</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>19.20</ans:valorUnitario>
              <ans:valorTotal>38.40</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>4</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>15:15:28</ans:horaInicial>
              <ans:horaFinal>15:45:28</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501128</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PAQUIMETRIA ULTRASS?NICA - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>29.66</ans:valorUnitario>
              <ans:valorTotal>29.66</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>5</ans:sequencialItem>
              <ans:dataExecucao>2026-08-14</ans:dataExecucao>
              <ans:horaInicial>15:55:28</ans:horaInicial>
              <ans:horaFinal>16:25:28</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41501128</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PAQUIMETRIA ULTRASS?NICA - MONOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>20.76</ans:valorUnitario>
              <ans:valorTotal>20.76</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>11593380780</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>LEONARDO VIEIRA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>15230</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>232.72</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>232.72</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>326305</ans:registroANS>
            <ans:numeroGuiaPrestador>525265805</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>525265805</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-08-28</ans:dataAutorizacao>
            <ans:senha>CO2026009400503</ans:senha>
            <ans:dataValidadeSenha>2026-10-28</ans:dataValidadeSenha>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>087977830</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>EDUARDO JABOUR MOULIN</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>5257</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-08-28</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>H521 - MIOPIA</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>17227534</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>04</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-08-28</ans:dataExecucao>
              <ans:horaInicial>08:16:17</ans:horaInicial>
              <ans:horaFinal>08:46:17</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>98</ans:codigoTabela>
                <ans:codigoProcedimento>91000184</ans:codigoProcedimento>
                <ans:descricaoProcedimento>PCT CONSULTA OFTALMOLOGIA BASICA [C/HNN]</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>95.30</ans:valorUnitario>
              <ans:valorTotal>95.30</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>99501546772</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>EDUARDO JABOUR MOULIN</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>5257</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>95.30</ans:valorProcedimentos>
            <ans:valorTaxasAlugueis>0.00</ans:valorTaxasAlugueis>
            <ans:valorMateriais>0.00</ans:valorMateriais>
            <ans:valorMedicamentos>0.00</ans:valorMedicamentos>
            <ans:valorOPME>0.00</ans:valorOPME>
            <ans:valorGasesMedicinais>0.00</ans:valorGasesMedicinais>
            <ans:valorTotalGeral>95.30</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
      </ans:guiasTISS>
    </ans:loteGuias>
  </ans:prestadorParaOperadora>
</ans:mensagemTISS>`;

let semHash = xml;
semHash = semHash.replace(/<(?:[^:>]+:)?hash(?:\s*\/>|>[\s\S]*?<\/(?:[^:>]+:)?hash>)/gi, '');
semHash = semHash.replace(/>\s+</g, '><');
const matches = [];
const regex = />([^<]+)</g;
let m;
while ((m = regex.exec(semHash)) !== null) {
  const texto = m[1];
  if (texto.trim().length > 0) {
    matches.push(texto);
  }
}
const stringValores = matches.join('').trim();
const hash = SparkMD5.hash(stringValores).toLowerCase();
console.log("Calculated hash:", hash);

