export const SAMPLE_GUIA_SADT_SEM_HIFEN = `<?xml version='1.0' encoding='ISO-8859-1'?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas">
  <ans:cabecalho>
    <ans:identificacaoTransacao>
      <ans:tipoTransacao>ENVIO_LOTE_GUIAS</ans:tipoTransacao>
      <ans:sequencialTransacao>1000001</ans:sequencialTransacao>
      <ans:dataRegistroTransacao>2026-08-20</ans:dataRegistroTransacao>
      <ans:horaRegistroTransacao>09:00:00</ans:horaRegistroTransacao>
    </ans:identificacaoTransacao>
    <ans:origem>
      <ans:identificacaoPrestador>
        <ans:CNPJ>11222333000144</ans:CNPJ>
      </ans:identificacaoPrestador>
    </ans:origem>
    <ans:destino>
      <ans:registroANS>111111</ans:registroANS>
    </ans:destino>
    <ans:Padrao>4.01.00</ans:Padrao>
  </ans:cabecalho>
  <ans:prestadorParaOperadora>
    <ans:loteGuias>
      <ans:numeroLote>500001</ans:numeroLote>
      <ans:guiasTISS>
        <ans:guiaSADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>111111</ans:registroANS>
            <ans:numeroGuiaPrestador>7000001</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>12345678900011122</ans:numeroCarteira>
          </ans:dadosBeneficiario>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:dataExecucao>2026-08-19</ans:dataExecucao>
              <ans:procedimento>
                <ans:codigoProcedimento>40901114</ans:codigoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:valorUnitario>200.00</ans:valorUnitario>
              <ans:valorTotal>200.00</ans:valorTotal>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotalGeral>200.00</ans:valorTotalGeral>
        </ans:guiaSADT>
      </ans:guiasTISS>
    </ans:loteGuias>
  </ans:prestadorParaOperadora>
  <ans:epilogo>
    <ans:hash>d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0</ans:hash>
  </ans:epilogo>
</ans:mensagemTISS>`;

export const SAMPLE_GUIA_SPSADT_SEM_NAMESPACE = `<?xml version='1.0' encoding='ISO-8859-1'?>
<mensagemTISS xmlns="http://www.ans.gov.br/padroes/tiss/schemas">
  <cabecalho>
    <identificacaoTransacao>
      <tipoTransacao>ENVIO_LOTE_GUIAS</tipoTransacao>
      <sequencialTransacao>1000002</sequencialTransacao>
      <dataRegistroTransacao>2026-08-20</dataRegistroTransacao>
      <horaRegistroTransacao>09:10:00</horaRegistroTransacao>
    </identificacaoTransacao>
    <origem>
      <identificacaoPrestador>
        <CNPJ>11222333000144</CNPJ>
      </identificacaoPrestador>
    </origem>
    <destino>
      <registroANS>111111</registroANS>
    </destino>
    <Padrao>3.05.00</Padrao>
  </cabecalho>
  <prestadorParaOperadora>
    <loteGuias>
      <numeroLote>500002</numeroLote>
      <guiasTISS>
        <guiaSPSADT>
          <cabecalhoGuia>
            <registroANS>111111</registroANS>
            <numeroGuiaPrestador>7000002</numeroGuiaPrestador>
          </cabecalhoGuia>
          <dadosBeneficiario>
            <numeroCarteira>99988877700011122</numeroCarteira>
          </dadosBeneficiario>
          <procedimentosExecutados>
            <procedimentoExecutado>
              <dataExecucao>2026-08-19</dataExecucao>
              <procedimento>
                <codigoProcedimento>41101014</codigoProcedimento>
              </procedimento>
              <quantidadeExecutada>1</quantidadeExecutada>
              <valorUnitario>350.00</valorUnitario>
              <valorTotal>350.00</valorTotal>
            </procedimentoExecutado>
          </procedimentosExecutados>
          <valorTotalGeral>350.00</valorTotalGeral>
        </guiaSPSADT>
      </guiasTISS>
    </loteGuias>
  </prestadorParaOperadora>
  <epilogo>
    <hash>e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1</hash>
  </epilogo>
</mensagemTISS>`;
