export const SAMPLE_TISS_WITH_ERRORS = `<?xml version="1.0" encoding="ISO-8859-1"?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas">
  <ans:cabecalho>
    <ans:identificacaoTransacao>
      <ans:tipoTransacao>ENVIO_LOTE_GUIAS</ans:tipoTransacao>
      <ans:sequencialTransacao>849201</ans:sequencialTransacao>
      <ans:dataRegistroTransacao>2026-08-05</ans:dataRegistroTransacao>
      <ans:horaRegistroTransacao>10:30:00</ans:horaRegistroTransacao>
    </ans:identificacaoTransacao>
    <ans:origem>
      <ans:identificacaoPrestador>
        <ans:cnpjContratado>12345678000195</ans:cnpjContratado>
      </ans:identificacaoPrestador>
    </ans:origem>
    <ans:destino>
      <ans:registroANS>358291</ans:registroANS>
    </ans:destino>
    <ans:Padrao>3.05.00</ans:Padrao>
  </ans:cabecalho>
  <ans:prestadorParaOperadora>
    <ans:loteGuias>
      <ans:numeroLote>009182</ans:numeroLote>
      <ans:guiasTISS>
        <ans:guiaConsulta>
          <ans:cabecalhoConsulta>
            <ans:registroANS>358291</ans:registroANS>
            <ans:numeroGuiaOperadora>987654321</ans:numeroGuiaOperadora>
          </ans:cabecalhoConsulta>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>00112233445566</ans:numeroCarteira>
            <ans:nomeBeneficiario>CARLOS ALBERTO SILVA</ans:nomeBeneficiario>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:contratadoExecutante>
            <ans:cnpjContratado>12345678000195</ans:cnpjContratado>
            <ans:CNPJ>12345678000195</ans:CNPJ>
          </ans:contratadoExecutante>
          <ans:dadosAtendimento>
            <ans:dataAtendimento>2026-08-01</ans:dataAtendimento>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:procedimento>
              <ans:codigoProcedimento>10101012</ans:codigoProcedimento>
              <ans:valorProcedimento>150,00</ans:valorProcedimento>
            </ans:procedimento>
          </ans:dadosAtendimento>
          <ans:regimeAtendimento>01</ans:regimeAtendimento>
        </ans:guiaConsulta>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>358291</ans:registroANS>
            <ans:numeroGuiaOperadora>554433221</ans:numeroGuiaOperadora>
          </ans:cabecalhoGuia>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>99887766554433</ans:numeroCarteira>
            <ans:nomeBeneficiario>MARIA EDUARDA SANTOS</ans:nomeBeneficiario>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:cnpjContratado>12345678000195</ans:cnpjContratado>
          </ans:dadosSolicitante>
          <ans:dadosExame>
            <ans:tecnicaUtilizada>ULTRASSONOGRAFIA</ans:tecnicaUtilizada>
            <ans:indicacaoClinica>DORES ABDOMINAIS</ans:indicacaoClinica>
            <ans:observacao></ans:observacao>
            <ans:procedimentoExame>
              <ans:codigoProcedimento>40801010</ans:codigoProcedimento>
              <ans:reducaoAcrescimo>0.70</ans:reducaoAcrescimo>
              <ans:valorTotalGeral>320,50</ans:valorTotalGeral>
            </ans:procedimentoExame>
          </ans:dadosExame>
        </ans:guiaSP-SADT>
      </ans:guiasTISS>
    </ans:loteGuias>
  </ans:prestadorParaOperadora>
  <ans:epilogo>
    <ans:hash>A1B2C3D4E5F678901234567890ABCDEF</ans:hash>
  </ans:epilogo>
</ans:mensagemTISS>`;

export const SAMPLE_MODELO_OPERADORA_SADT = `<?xml version='1.0' encoding='ISO-8859-1'?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas">
  <ans:cabecalho>
    <ans:identificacaoTransacao>
      <ans:tipoTransacao>ENVIO_LOTE_GUIAS</ans:tipoTransacao>
      <ans:sequencialTransacao>2011383</ans:sequencialTransacao>
      <ans:dataRegistroTransacao>2026-08-10</ans:dataRegistroTransacao>
      <ans:horaRegistroTransacao>16:40:20</ans:horaRegistroTransacao>
    </ans:identificacaoTransacao>
    <ans:origem>
      <ans:identificacaoPrestador>
        <ans:CNPJ>01137028000138</ans:CNPJ>
      </ans:identificacaoPrestador>
    </ans:origem>
    <ans:destino>
      <ans:registroANS>006246</ans:registroANS>
    </ans:destino>
    <ans:Padrao>4.02.00</ans:Padrao>
  </ans:cabecalho>
  <ans:prestadorParaOperadora>
    <ans:loteGuias>
      <ans:numeroLote>3610549</ans:numeroLote>
      <ans:guiasTISS>
        <ans:guiaSP-SADT>
          <ans:cabecalhoGuia>
            <ans:registroANS>006246</ans:registroANS>
            <ans:numeroGuiaPrestador>7700007648</ans:numeroGuiaPrestador>
          </ans:cabecalhoGuia>
          <ans:dadosAutorizacao>
            <ans:numeroGuiaOperadora>7700007648</ans:numeroGuiaOperadora>
            <ans:dataAutorizacao>2026-07-07</ans:dataAutorizacao>
          </ans:dadosAutorizacao>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>56788888470114410021</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:dadosSolicitante>
            <ans:contratadoSolicitante>
              <ans:codigoPrestadorNaOperadora>011370280001</ans:codigoPrestadorNaOperadora>
            </ans:contratadoSolicitante>
            <ans:nomeContratadoSolicitante>CCOLHOS - CENTRO CAPIXABA DE OLHOS LTDA</ans:nomeContratadoSolicitante>
            <ans:profissionalSolicitante>
              <ans:nomeProfissional>GRACE PACHECO DE SOUZA</ans:nomeProfissional>
              <ans:conselhoProfissional>06</ans:conselhoProfissional>
              <ans:numeroConselhoProfissional>5355</ans:numeroConselhoProfissional>
              <ans:UF>32</ans:UF>
              <ans:CBOS>225265</ans:CBOS>
            </ans:profissionalSolicitante>
          </ans:dadosSolicitante>
          <ans:dadosSolicitacao>
            <ans:dataSolicitacao>2026-07-07</ans:dataSolicitacao>
            <ans:caraterAtendimento>1</ans:caraterAtendimento>
            <ans:indicacaoClinica>Z010 - EXAME DOS OLHOS E DA VISAO</ans:indicacaoClinica>
          </ans:dadosSolicitacao>
          <ans:dadosExecutante>
            <ans:contratadoExecutante>
              <ans:codigoPrestadorNaOperadora>011370280001</ans:codigoPrestadorNaOperadora>
            </ans:contratadoExecutante>
            <ans:CNES>3891542</ans:CNES>
          </ans:dadosExecutante>
          <ans:dadosAtendimento>
            <ans:tipoAtendimento>23</ans:tipoAtendimento>
            <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
          </ans:dadosAtendimento>
          <ans:procedimentosExecutados>
            <ans:procedimentoExecutado>
              <ans:sequencialItem>1</ans:sequencialItem>
              <ans:dataExecucao>2026-07-07</ans:dataExecucao>
              <ans:horaInicial>14:55:04</ans:horaInicial>
              <ans:horaFinal>15:25:04</ans:horaFinal>
              <ans:procedimento>
                <ans:codigoTabela>22</ans:codigoTabela>
                <ans:codigoProcedimento>41301323</ans:codigoProcedimento>
                <ans:descricaoProcedimento>TONOMETRIA BINOCULAR</ans:descricaoProcedimento>
              </ans:procedimento>
              <ans:quantidadeExecutada>1</ans:quantidadeExecutada>
              <ans:tecnicaUtilizada>1</ans:tecnicaUtilizada>
              <ans:reducaoAcrescimo>1.00</ans:reducaoAcrescimo>
              <ans:valorUnitario>10.50</ans:valorUnitario>
              <ans:valorTotal>10.50</ans:valorTotal>
              <ans:equipeSadt>
                <ans:grauPart>12</ans:grauPart>
                <ans:codProfissional>
                  <ans:cpfContratado>00016731735</ans:cpfContratado>
                </ans:codProfissional>
                <ans:nomeProf>GRACE PACHECO DE SOUZA</ans:nomeProf>
                <ans:conselho>06</ans:conselho>
                <ans:numeroConselhoProfissional>5355</ans:numeroConselhoProfissional>
                <ans:UF>32</ans:UF>
                <ans:CBOS>225265</ans:CBOS>
              </ans:equipeSadt>
            </ans:procedimentoExecutado>
          </ans:procedimentosExecutados>
          <ans:valorTotal>
            <ans:valorProcedimentos>10.50</ans:valorProcedimentos>
            <ans:valorTotalGeral>10.50</ans:valorTotalGeral>
          </ans:valorTotal>
        </ans:guiaSP-SADT>
      </ans:guiasTISS>
    </ans:loteGuias>
  </ans:prestadorParaOperadora>
  <ans:epilogo>
    <ans:hash>c133d8ea00829ec3cafbeb4b7f532162</ans:hash>
  </ans:epilogo>
</ans:mensagemTISS>`;

export const SAMPLE_TISS_4_SADT = SAMPLE_MODELO_OPERADORA_SADT;

export const SAMPLE_MODELO_OPERADORA_CONSULTA = `<?xml version='1.0' encoding='ISO-8859-1'?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas">
  <ans:cabecalho>
    <ans:identificacaoTransacao>
      <ans:tipoTransacao>ENVIO_LOTE_GUIAS</ans:tipoTransacao>
      <ans:sequencialTransacao>2010939</ans:sequencialTransacao>
      <ans:dataRegistroTransacao>2026-08-10</ans:dataRegistroTransacao>
      <ans:horaRegistroTransacao>12:54:46</ans:horaRegistroTransacao>
    </ans:identificacaoTransacao>
    <ans:origem>
      <ans:identificacaoPrestador>
        <ans:CNPJ>01137028000138</ans:CNPJ>
      </ans:identificacaoPrestador>
    </ans:origem>
    <ans:destino>
      <ans:registroANS>333689</ans:registroANS>
    </ans:destino>
    <ans:Padrao>4.01.00</ans:Padrao>
  </ans:cabecalho>
  <ans:prestadorParaOperadora>
    <ans:loteGuias>
      <ans:numeroLote>3602182</ans:numeroLote>
      <ans:guiasTISS>
        <ans:guiaConsulta>
          <ans:cabecalhoConsulta>
            <ans:registroANS>333689</ans:registroANS>
            <ans:numeroGuiaPrestador>35905236</ans:numeroGuiaPrestador>
          </ans:cabecalhoConsulta>
          <ans:numeroGuiaOperadora>35905236</ans:numeroGuiaOperadora>
          <ans:dadosBeneficiario>
            <ans:numeroCarteira>000747385106472202</ans:numeroCarteira>
            <ans:atendimentoRN>N</ans:atendimentoRN>
          </ans:dadosBeneficiario>
          <ans:contratadoExecutante>
            <ans:cnpjContratado>01137028000138</ans:cnpjContratado>
            <ans:CNES>3891542</ans:CNES>
          </ans:contratadoExecutante>
          <ans:profissionalExecutante>
            <ans:nomeProfissional>RUBENS MACHADO</ans:nomeProfissional>
            <ans:conselhoProfissional>06</ans:conselhoProfissional>
            <ans:numeroConselhoProfissional>6158</ans:numeroConselhoProfissional>
            <ans:UF>32</ans:UF>
            <ans:CBOS>225265</ans:CBOS>
          </ans:profissionalExecutante>
          <ans:indicacaoAcidente>9</ans:indicacaoAcidente>
          <ans:dadosAtendimento>
            <ans:regimeAtendimento>01</ans:regimeAtendimento>
            <ans:dataAtendimento>2026-08-03</ans:dataAtendimento>
            <ans:tipoConsulta>1</ans:tipoConsulta>
            <ans:procedimento>
              <ans:codigoTabela>22</ans:codigoTabela>
              <ans:codigoProcedimento>10101012</ans:codigoProcedimento>
              <ans:valorProcedimento>134.79</ans:valorProcedimento>
            </ans:procedimento>
          </ans:dadosAtendimento>
        </ans:guiaConsulta>
      </ans:guiasTISS>
    </ans:loteGuias>
  </ans:prestadorParaOperadora>
  <ans:epilogo>
    <ans:hash>ca51801b1bcf0722f233b8340c1a812c</ans:hash>
  </ans:epilogo>
</ans:mensagemTISS>`;

